### ISSUE TITLE
pFabCircleColor and setProgressColor doesn't apply the color.

### ISSUE THREAD

**Issue by Christophe668** [dmallcott/ProgressFloatingActionButton#1]
Hi, 

I noticed the the method `setProgressColor()` is only changing the value of mColor and not applying the color to the _paint_ object in `ProgressView`. 

The color of the circle will always be set to the primary color fetch from the theme with `getThemePrimaryColor`.

Many thanks

**Comment by dmallcott** [comment]
Hey Christophe, I will look into this ASAP. Thank you for pointing it out.

**Comment by Christophe668** [comment]
Great thx!

**Comment by dmallcott** [comment]
I'm very sorry for the delay but I just pushed the quick fix.

**Comment by Christophe668** [comment]
Thank you so much, don't worry about that!
